config/routes.rb
Rails3SubdomainDevise::Application.routes.draw do

  get "sites/show"

  devise_for :users
  resources :users, :only => [:index, :show] do
    resources :subdomains, :shallow => true
  end
  match '/' => 'sites#show', :constraints => { :subdomain => /.+/ }
 root :to => "home#index"

end

app/models/site.rb
class Site < Subdomain
end

app/models/subdomain.rb
class Subdomain < ActiveRecord::Base
  belongs_to :user

  has_friendly_id :name, :use_slug => true, :strip_non_ascii => true
  validates_uniqueness_of :name, :case_sensitive => false
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :subdomains, :dependent => :destroy
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me , :name

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false

  has_friendly_id :name, :use_slug => true, :strip_non_ascii => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def show
    @site = Site.find_by_name!(request.subdomain)
  end

end

app/controllers/subdomains_controller.rb
class SubdomainsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_user, :except => [:index, :show]
  respond_to :html

  def index
    @subdomains = Subdomain.all
    respond_with(@subdomains)
  end

  def show
    @subdomain = Subdomain.find(params[:id])
    respond_with(@subdomain)
  end

  def new
    @subdomain = Subdomain.new(:user => @user)
    respond_with(@subdomain)
  end

  def create
    @subdomain = Subdomain.new(params[:subdomain])
    if @subdomain.save
      flash[:notice] = "Successfully created subdomain."
    end
    redirect_to @user
  end

  def edit
    @subdomain = Subdomain.find(params[:id])
    respond_with(@subdomain)
  end

  def update
    @subdomain = Subdomain.find(params[:id])
    if @subdomain.update_attributes(params[:subdomain])
      flash[:notice] = "Successfully updated subdomain."
    end
    respond_with(@subdomain)
  end

  def destroy
    @subdomain = Subdomain.find(params[:id])
    @subdomain.destroy
    flash[:notice] = "Successfully destroyed subdomain."
    redirect_to @user
  end

  protected

  def find_user
    if params[:user_id]
      @user = User.find(params[:user_id])
    else
      @subdomain = Subdomain.find(params[:id])
      @user = @subdomain.user
    end
    unless current_user == @user
      redirect_to @user, :alert => "Are you logged in properly? You are not allowed to create or change someone else's subdomain."
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/subdomains_helper.rb
module SubdomainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Rails3-Subdomain-Devise</h1>
<p><%= link_to "View List of Users", users_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3SubdomainDevise</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>

  <%= csrf_meta_tag %>
</head>
<body>
<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/sites/show.html.erb
<h1>Site: <%= @site.name %></h1>
<p>Belongs to: <%= link_to @site.user.name, user_url(@site.user) %></p>

app/views/subdomains/_form.html.erb
<% if @subdomain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subdomain.errors.count, "error") %> prohibited this subdomain from being saved:</h2>
      <ul>
        <% @subdomain.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= fields_for @subdomain do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.hidden_field(:user_id, :value => @subdomain.user_id) %>
    </div>
    <br />
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/subdomains/edit.html.erb
<h1>Editing subdomain</h1>
<%= form_for(@subdomain) do |f| %>
    <%= render 'form' %>
<% end %><%= link_to 'Show', @subdomain %> |
<%= link_to @subdomain.user.name, user_path(@subdomain.user) %>

app/views/subdomains/index.html.erb
<h1>Subdomains</h1>
<table>
  <% @subdomains.each do |subdomain| %>
      <tr>
        <td><%= link_to subdomain.name, subdomain %></td>
        <td>(belongs to <%= link_to subdomain.user.name, user_url(subdomain.user) %>)</td>
        <td><%= link_to 'Edit', edit_subdomain_path(subdomain) %></td>
        <td><%= link_to 'Destroy', subdomain, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>

app/views/subdomains/new.html.erb
<h1>New subdomain</h1>
<%= form_for([@user, @subdomain]) do |f| %>
    <%= render 'form' %>
<% end %>
<%= link_to @subdomain.user.name, user_path(@subdomain.user) %>

app/views/subdomains/show.html.erb
<h1><%= @subdomain.name %></h1>
<p>Belongs to: <%= link_to @subdomain.user.name, user_url(@subdomain.user) %></p>
<%= link_to 'Edit', edit_subdomain_path(@subdomain) %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
      </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>Email: <%= @user.email %></p>
<%= link_to 'Edit', edit_user_registration_path %> |
<%= link_to 'List of Users', users_path %>
<h3><%= @user.name %>'s Subdomains</h3>
<table>
  <% @user.subdomains.each do |subdomain| %>
      <tr>
        <td><%= link_to subdomain.name, subdomain %></td>
        <td><%= link_to 'Edit', edit_subdomain_path(subdomain) %></td>
        <td><%= link_to 'Destroy', subdomain, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>
<br />
<%= link_to "Add New Subdomain", new_user_subdomain_path(@user) %>